### ISSUE TITLE
Request for a "Get Started" Tutorial

### ISSUE THREAD

**Issue by CasperHK** [go-gl/mathgl#62] opened 2016-11-19 07:28 UTC
deleted. You can close this post. Thank you.

**Comment by shurcooL** [comment] 2016-11-24 16:38
The body says "deleted", so I'm not sure what to make of this. The issue is still open, did you mean to close this?

**Comment by shurcooL** [comment] 2016-11-24 16:40
As far as getting started, I would recommend reading the README, and then the godoc page for one of the packages, e.g.:

https://godoc.org/github.com/go-gl/mathgl/mgl64

This is simply a collection of math utilities meant for graphics programming and similar. It's heavily inspired by the excellent C++ library called glm by @Groovounet:

http://glm.g-truc.net/0.9.8/index.html

**Closed** 2019-05-05 00:10 UTC
